default:
  -
    scope:
      path: ""
      type: pages
    values:
      layout: "default"
      author: Joel Cumberland

posts_lists:
  -
    scope:
      path: "/posts/"
      type: posts
      paginate: 1
      paginate_path: "posts/page:num/"
    values:
      layout: "post_lists"
      author: Joel Cumberland

analytics :
    provider : google
      google :
      tracking_id : 'UA-58456085-1'
