--- 
analytics: 
  - 
    google: 
      tracking_id: UA-58456085-1
    provider: google
default: 
  - 
    scope: 
      path: ""
      type: pages
    values: 
      author: "Joel Cumberland"
      layout: default
posts_lists: 
  - 
    scope: 
      paginate: 1
      paginate_path: "posts/page:num/"
      path: /posts/
      type: posts
    values: 
      author: "Joel Cumberland"
      layout: post_lists
